### ISSUE TITLE
Add texteditor to Description 

### ISSUE THREAD

**Issue by aniljailta** [zasyadev/zasya-saas-review-app#168]
We should be adding text editor for adding Description for creating a review or goal , wherever i think para is getting added . 
can have something like github have for comments as well . 

<img width="846" alt="Screenshot 2023-06-20 at 11 57 35 AM" src="https://github.com/zasyadev/zasya-saas-review-app/assets/6049696/861b3292-8648-4988-806c-f308d6722efd">

**Comment by kshitijzasya** [comment]
Tracking this issue on https://zasyasolutions.bitrix24.in/workgroups/group/12/tasks/task/view/78/
