### ISSUE TITLE
Button position at top

### ISSUE THREAD

**Issue by aniljailta** [zasyadev/zasya-saas-review-app#169]
we should have a centralised position for buttons . like adding a follow up button is at bottom which doesn;t make any sense . 

align it with other buttons . also admin should have option to change their statues as well , like if i would like to mark it as complete . i should have the option . 

<img width="1317" alt="Screenshot 2023-06-20 at 12 00 53 PM" src="https://github.com/zasyadev/zasya-saas-review-app/assets/6049696/03dbac5f-1620-4bc8-8396-24063bc68b53">

**Comment by zasyadev** [comment]
Tracking this on: https://zasyasolutions.bitrix24.in/workgroups/group/12/tasks/task/view/88/
