### ISSUE TITLE
Centralise place for Slack

### ISSUE THREAD

**Issue by aniljailta** [zasyadev/zasya-saas-review-app#170]
I think we will have to create some kind on integration section where we will adding integration for third party tools . 

For slack i think it require better integration as adding email won't be enough , let's say if user is having multiple workspace with same email , which workspace will we be sending these notifcations ? 

Going forward we can add more third party libraries to it 

<img width="487" alt="Screenshot 2023-06-20 at 12 07 16 PM" src="https://github.com/zasyadev/zasya-saas-review-app/assets/6049696/2764fa07-1789-4988-99bf-665357c9403b">

**Comment by kshitijzasya** [comment]
Tracking this task on https://zasyasolutions.bitrix24.in/workgroups/group/12/tasks/task/view/116/
