### ISSUE TITLE
rectify activity messaging 

### ISSUE THREAD

**Issue by aniljailta** [zasyadev/zasya-saas-review-app#171]
<img width="809" alt="Screenshot 2023-06-20 at 12 14 49 PM" src="https://github.com/zasyadev/zasya-saas-review-app/assets/6049696/5fa054a0-2435-44cf-ac2d-02bb6d8ce5df">

**Comment by kshitijzasya** [comment]
Tracking this issue on https://zasyasolutions.bitrix24.in/workgroups/group/12/tasks/task/view/80/
