### ISSUE TITLE
Improve create user process 

### ISSUE THREAD

**Issue by aniljailta** [zasyadev/zasya-saas-review-app#172]
When we are creating new user . tag should be converted to group . need to merge tags with group . 
also when i click on teams , it gives option to create new group , but just to make it better and feel connected to website , we will have give this teams feature in Users part only and merge it with users . 

At top give total users count and next to it show team group count . and option to create new team/group on same page to better streamline it . 

Also when i go to create review , i don't see option to select group or team and on assign review select box , all team members are not getting displayed or when i scroll down . 
<img width="1314" alt="Screenshot 2023-06-27 at 4 22 35 PM" src="https://github.com/zasyadev/zasya-saas-review-app/assets/6049696/8347e423-3f31-48f6-b20c-8575f7c08e52">

<img width="895" alt="Screenshot 2023-06-27 at 4 22 22 PM" src="https://github.com/zasyadev/zasya-saas-review-app/assets/6049696/338afedc-e865-40ec-b679-8c87934fd0a5">

**Comment by kshitijzasya** [comment]
Tracking this issue on https://zasyasolutions.bitrix24.in/workgroups/group/12/tasks/task/view/118/
