### ISSUE TITLE
give remind again on invite option 

### ISSUE THREAD

**Issue by aniljailta** [zasyadev/zasya-saas-review-app#173]
Need to give remind again feature if in case user hasn't accepted your invite 

<img width="1314" alt="Screenshot 2023-06-27 at 4 20 53 PM" src="https://github.com/zasyadev/zasya-saas-review-app/assets/6049696/c186cebe-a749-4ef4-adcc-cc89a8c4231e">

**Comment by kshitijzasya** [comment]
Tracking this issue on https://zasyasolutions.bitrix24.in/workgroups/group/12/tasks/task/view/82/
