### ISSUE TITLE
Option to create another workspace and switch between them 

### ISSUE THREAD

**Issue by aniljailta** [zasyadev/zasya-saas-review-app#174]
Need to give option to switch between workspace . 

So on different workspaces we can have different roles . 

<img width="224" alt="Screenshot 2023-06-27 at 5 33 01 PM" src="https://github.com/zasyadev/zasya-saas-review-app/assets/6049696/c40d3e7d-b2e8-4126-9f20-f5dee20eac44">

**Comment by kshitijzasya** [comment]
tracking this task on https://zasyasolutions.bitrix24.in/workgroups/group/12/tasks/task/view/108/
