### ISSUE TITLE
wrong timestamp 

### ISSUE THREAD

**Issue by aniljailta** [zasyadev/zasya-saas-review-app#30]
<img width="338" alt="Screenshot 2022-11-17 at 1 16 46 PM" src="https://user-images.githubusercontent.com/6049696/202386870-98c75711-4d0e-464f-ae37-4e1714016c08.png">
Please test time in review detail page , it shows wrong time . like in above file person who filled review yesterday are showing as 5 or 10mins ago and latest one are shown as in above screenshot

**Comment by kshitijzasya** [comment]
It's a user reactivity time
